radareorg/iaito

.github/workflows/ccpp.yml

Update radare2 to latest commit in master

---

.github/workflows/ccpp.yml
build.sh
docker/Dockerfile
prepare_r2.bat
scripts/fetch_deps.sh

Add apt-update

---

src/Cutter.pro
src/lib_radare2.pri

asdjdfklajskl

---

src/common/Decompiler.cpp

Fix warning

---

README.md

Hello please can we add overview of the linux package versions to the readme?
Thank you

Overview of the Linux package versions

---

Makefile
dist/macos/make-macos-pkg.sh

attempt to fix

---

src/org.radare.r2cutter.appdata.xml

cutter -> re2cutter renaming

---

src/widgets/DebugActions.cpp

Just replaced link to rizin issues with issues of this repo

Updated link to issues in debugger

---

src/CMakeLists.txt
src/iaito.1

- install manpage
- install the appdata.xml
The appdata xml is used by tools like Gnome Software.
Also removed desktop launcher from the Devel component ... as launcher
should be part of the binary installation and not the Devel package.

Add manpage, install appdata.xml

---

.github/workflows/ci.yml
prepare_r2.bat

Upgrade to 5.3.1

---

README.md

https://www.mail-archive.com/ubuntu-bugs@lists.ubuntu.com/msg5902890.html
This dependency should be updated. The package qt5-default is now obsolete and has been dropped upstream in Debian and will not be available in the hirsute release.
```sh
sudo apt install qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools
```
None

package qt5-default is now obsolete

---

src/core/Iaito.cpp
src/core/Iaito.h
src/dialogs/AttachProcDialog.cpp
src/widgets/DebugActions.cpp

Use o. instead of file.path

---

src/dialogs/HexdumpRangeDialog.cpp
src/widgets/BreakpointWidget.cpp
src/widgets/GraphGridLayout.cpp
src/widgets/GraphHorizontalAdapter.cpp
src/widgets/ImportsWidget.cpp
src/widgets/RelocsWidget.cpp
src/widgets/ResourcesWidget.cpp

Fix type issues

---

docker/Dockerfile
docker/Dockerfile-dev
docker/Makefile
docker/entrypoint.sh

I Just added patch into Dockerfile and renamed Iaito to iaito in building scripts and entrypoints
$ cd ./docker && make build && make run.
After it iaito will be ran.

Modified docker files because Iaito is built as iaito

---

src/dialogs/SaveProjectDialog.cpp

Change prj.git to prj.vc due to the following commit in radare2:
https://github.com/radareorg/radare2/commit/4682d70dc0bf59cc017446446eab48d33e03310e

Change prj.git to prj.vc due to the following commit in radare2:

---

src/common/ColorThemeWorker.cpp
src/common/ResourcePaths.cpp

Two fixes in order to support the new radare version not yet published and localisations in Flatpak.

Flatpak fixes

---

src/org.radare.iaito.appdata.xml

Merged your appdata with the one from flatpak

Fix appdata

---

README.md

Add flatpak badge and link into readme file.

Add flathub information in README

---

.github/workflows/ci.yml
.gitignore
.gitmodules
Makefile
README.md
build.sh
configure.bat
dist/debian/iaito/Makefile
dist/macos/make-macos-app.sh
dist/macos/make-macos-pkg.sh
docker/Dockerfile
preconfigure
scripts/deploy_translations.sh
src/Iaito.pro

Disabled translations submodule but maintaining generating translations when compiling by CI and as much as back compatible as possible.

Disable translations submodule

---

.github/workflows/ci.yml

Upgrade the github runners

---

src/common/AnalTask.cpp
src/common/FunctionsTask.h
src/common/StringsTask.h
src/core/Iaito.cpp
src/core/Iaito.h
src/core/MainWindow.cpp
src/dialogs/InitialOptionsDialog.cpp
src/widgets/ConsoleWidget.cpp
src/widgets/FunctionsWidget.cpp
src/widgets/StringsWidget.cpp

Fix all race conditions by making iaito monothread by default

---

src/widgets/ImportsWidget.cpp

**Checklist**
Fixing an empty Import table

Fixing an empty Import table

---

.github/workflows/ci.yml
src/common/AnalTask.cpp
src/common/InitialOptions.h
src/dialogs/InitialOptionsDialog.cpp
src/dialogs/InitialOptionsDialog.ui

Support 5a analysis like in latest r2 and add checkbox for anal.vars

---

.github/workflows/ci.yml
make.bat

Automate release process in the CI

---

.github/workflows/ci.yml
make.bat
src/Iaito.pro

Try release builds for windows in the CI

---

src/core/Iaito.cpp

**Checklist**
Rename of object in R2 commit 4a75b94b495207b158ebeb3397ab550cf261e76e reflected here.

Fix RBinFile->o renamed to RBinObject->bo

---

Makefile
README.md
src/CorePlugin.cpp
src/IaitoApplication.cpp
src/Main.cpp
src/common/Helpers.cpp
src/common/Helpers.h
src/core/Iaito.cpp
src/core/MainWindow.cpp
src/core/MainWindow.h

Initial support for running iaito frominside r2

---

dist/debian/CONFIG
dist/debian/getpkgversions.sh

**Checklist**
* Adds a small script to build a list of versioned list of dependencies because which versions Github uses is unknown to me
* Adds dependent packages to `dist/debian/CONFIG` file
I've tested this as much as possible but I cannot be sure this will work as building packages is done by Github.

Add dependencies for CONFIG

---

Makefile
src/lib_radare2.pri

Link against r_arch when using qmake

---

src/widgets/DisassemblyWidget.cpp
src/widgets/DisassemblyWidget.h

Zoom font size with control+wheel in the disassembly widget

---

.github/workflows/ci.yml

Update teh CI

---

src/Iaito.pro
src/IaitoApplication.cpp
src/common/R2DecaiDecompiler.cpp
src/common/R2DecaiDecompiler.h

Initial support for the Decai decompiler

---

src/Iaito.pro
src/IaitoApplication.cpp
src/common/R2AnotesDecompiler.cpp
src/common/R2AnotesDecompiler.h

* TODO: add button to edit those notes
* TODO: check r2 version for availability of the feature
**Checklist**

Add ano support as an alternative decompiler

---

src/core/MainWindow.cpp
src/widgets/DebugActions.cpp
src/widgets/DebugActions.h

Add an option to edit the rarun profile

---

.github/workflows/ci.yml
src/Iaito.pro
src/common/TextEditDialog.cpp
src/common/TextEditDialog.h
src/core/Iaito.cpp
src/menus/DecompilerContextMenu.cpp
src/menus/DecompilerContextMenu.h
src/menus/DisassemblyContextMenu.cpp
src/menus/DisassemblyContextMenu.h

Add context menu to edit annotations in disasm

---

src/Iaito.pro
src/common/TextEditDialog.cpp
src/common/TypeScriptHighlighter.cpp
src/common/TypeScriptHighlighter.h
src/widgets/CodeEditor.cpp
src/widgets/CodeEditor.h

Add a WIP TypeScript CodeEditor widget

---

src/core/Iaito.cpp

Load radare2 plugins from the iaito plugins directory too

---

src/widgets/ConsoleWidget.cpp

Fixes the crash on Haiku on launch.

Fix crash on launch on Haiku

---

src/common/Configuration.cpp
src/common/TempConfig.cpp
src/widgets/AddressableItemList.h
src/widgets/BoolToggleDelegate.cpp

Use 'j/k' to move along functions

---

src/Iaito.pro

In order to fix #247
This PR tries to correct the issues detected by @i0ntempest on #233.
Also changing the include paths following the same spirit as the rpath ones.

Fix macos local builds
