radareorg/iaito

- src/menus/DecompilerContextMenu.cpp
Avoid warning message about potentially uninitialized variable "menu".
It is initialized in if/else so just nulling it on the beginning should do the trick.
[ 36%] Building CXX object CMakeFiles/r2cutter.dir/widgets/DisassemblyWidget.cpp.o
/usr/lib64/ccache/g++ -DCUTTER_ENABLE_GRAPHVIZ -DCUTTER_ENABLE_KSYNTAXHIGHLIGHTING -DCUTTER_SOURCE_BUILD -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_WIDGETS_LIB -Dr2cutter_EXPORTS -IBUILD/r2cutter-0.1.1/x86_64-redhat-linux-gnu -IBUILD/r2cutter-0.1.1/src -IBUILD/r2cutter-0.1.1/x86_64-redhat-linux-gnu/r2cutter_autogen/include -IBUILD/r2cutter-0.1.1/src/core -IBUILD/r2cutter-0.1.1/src/widgets -IBUILD/r2cutter-0.1.1/src/common -IBUILD/r2cutter-0.1.1/src/plugins -IBUILD/r2cutter-0.1.1/src/menus -IBUILD/r2cutter-0.1.1/src/. …
> Avoid warning about uninitialized menu

- src/widgets/ConsoleWidget.cpp
Added handling of the failed call to pipe function.
Related to https://github.com/radareorg/r2cutter/issues/10
[ 58%] Building CXX object CMakeFiles/r2cutter.dir/widgets/ProcessesWidget.cpp.o
/usr/lib64/ccache/g++ -DCUTTER_ENABLE_GRAPHVIZ -DCUTTER_ENABLE_KSYNTAXHIGHLIGHTING -DCUTTER_SOURCE_BUILD -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_WIDGETS_LIB -Dr2cutter_EXPORTS -I/home/mambroz/rpmbuild/BUILD/r2cutter-0.1.1/x86_64-redhat-linux-gnu -I/home/mambroz/rpmbuild/BUILD/r2cutter-0.1.1/src -I/home/mambroz/rpmbuild/BUILD/r2cutter-0.1.1/x86_64-redhat-linux-gnu/r2cutter_autogen/include -I/home/mambroz/rpmbuild/BUILD/r2cutter-0.1.1/src/core -I/home/mambroz/rpmbuild/BUILD/r2cutter-0.1.1/src/widgets -I/home/mambroz/rpmbuild/BUILD/r2cutter-0.1.1/src/common …
> Unhandled result of the pipe function

- src/plugins/PluginManager.cpp
The rebranding to iaito broke some things, like the python bindings. This fixes the header include and the IDX constant.
```
cmake -B build \
-DCMAKE_INSTALL_PREFIX=/usr \
-DCMAKE_BUILD_TYPE=None \
-DIAITO_ENABLE_PYTHON=ON \
-DIAITO_ENABLE_PYTHON_BINDINGS=ON \
-DIAITO_USE_BUNDLED_RADARE2=OFF \
-DIAITO_USE_ADDITIONAL_RADARE2_PATHS=OFF \
-DIAITO_ENABLE_CRASH_REPORTS=OFF \
-DIAITO_ENABLE_GRAPHVIZ=ON \
-Wno-dev \
-G Ninja
ninja -C build
```
> Fix python bindings compilation after rebranding

- src/CMakeLists.txt
In the kf5-syntax-highlighting-devel 5.91.0 the cmake files dropped advertising of the /usr/include/KF5 include directory.
As Iaito is referencing those with <KSyntaxHighlighting/repository.h> relative to /usr/include/KF5 we need to add this include directory in order to be able to compile successfully.
closes #70
> workaround missing include in kf5-syntax-highlighting-devel

- src/CMakeLists.txt
- src/common/Configuration.cpp
- src/common/SyntaxHighlighter.cpp
- src/common/SyntaxHighlighter.h
Mixing Camelcase and standard include wasn't the intended way.
This was fixed in syntax-highlighting 5.91.
Amends 24a2eba2
> Fix KSyntaxHighlighting includes.

- src/core/Iaito.cpp
This function was responsible for a segfault when loading any Windows binary
It now uses the API as the TODO above said.
Closes #60
> Fixed IaitoCore::getBreakpoints

- README.md
```sh
[17:08 edu@xps iaito]  (master)>  make
mkdir -p build
cd build && /usr/bin/qmake ../src/Iaito.pro 
Project ERROR: requires Qt 5
Makefile:55: recipe for target 'build' failed
make: *** [build] Error 2
```
> Add qt5-default as dependency on Ubuntu/Debian boxes

- src/org.radare.iaito.desktop
Having duplicate StartupNotify is making the desktop file invalid on some platforms and is not passing the sanity check for the Fedora package build https://kojipkgs.fedoraproject.org//work/tasks/9327/92669327/build.log
```
+ appstream-util validate-relax --nonet /builddir/build/BUILDROOT/iaito-5.7.6-1.fc38.x86_64/usr/share/metainfo/org.radare.iaito.appdata.xml /builddir/build/BUILDROOT/iaito-5.7.6-1.fc38.x86_64/usr/share/metainfo/org.radare.iaito.appdata.xml: OK
+ desktop-file-validate /builddir/build/BUILDROOT/iaito-5.7.6-1.fc38.x86_64//usr/share/applications/org.radare.iaito.desktop /builddir/build/BUILDROOT/iaito-5.7.6-1.fc38.x86_64//usr/share/applications/org.radare.iaito.desktop: hint: value item "Viewer" in key "Categories" in group "Desktop Entry" can be extended with another …
```
> remove duplicate StartupNotify=true

- Makefile
Moved to use the new install method from https://github.com/radareorg/iaito-translations/pull/1
Update: Needs to merge this PR https://github.com/radareorg/iaito-translations/pull/2 with the macOS fix.
> Update translation install method

- .github/workflows/ci.yml
**Checklist**
Changed path where CI was looking for macOS artifact, should now find them during a release. Also, fixed the Windows artifact having 'macos' in it's name.
> Fix release CI failing on macOS artifact upload

- dist/debian/CONFIG
- dist/debian/iaito/Makefile
**Checklist**
* The DEPENDS variable was being nullified in the Makefile.
* The proper syntax for executing a shell script from a makefile is now being used.
> Fixes dependencies for Debian packages generation

- src/widgets/RelocsWidget.cpp
For some subtleties of C++ constructors that are lost on me, making the RelocsWidget constructor look the same as the ExportsWidget constructor dodges a segfault at startup. I've tested this only on x86_64 Ubuntu 22.04.3
**Checklist**
- [ X] Mark this if you consider it ready to merge
> Issue #148: Make RelocsWidget constructor like ExportsWidget

- src/Iaito.pro
- src/common/R2Shims.h
- src/core/Iaito.cpp
**Checklist**
Fix compilation errors by using `r_bin_name_tostring` where needed.
> Add basic support for RBinName

- src/core/Iaito.h
**Checklist**
- [ x] Mark this if you consider it ready to merge (if it isn't can't I just make a draft pr instead of having this checkbox here?)
On some configurations, the compiler wants a type cast because it can't automatically cast 0 to one of the enum members
> Fix file dialog type, which sometimes breaks build [#152]

- src/org.radare.iaito.appdata.xml
This PR fixes the appstream metadata to comply to the latest spec.
Current master versions has this problems:
```console
$ appstreamcli  validate src/org.radare.iaito.appdata.xml 
I: org.radare.iaito:8: description-first-word-not-capitalized
W: org.radare.iaito:41: update-contact-no-mail pancake
I: org.radare.iaito:42: developer-name-tag-deprecated
I: org.radare.iaito:97: description-first-word-not-capitalized
I: org.radare.iaito:~: developer-info-missing
✘ Validation failed: warnings: 1, infos: 4
```
After this PR:
```console
$ appstreamcli  validate src/org.radare.iaito.appdata.xml 
✔ Validation was successful.
```
> Fix appdata metadata

- src/dialogs/NewFileDialog.cpp
Cleaner version of the PR in https://github.com/radareorg/iaito/pull/176 
It's still a fix for the ticket https://github.com/radareorg/iaito/issues/174
I made two versions because for me this is the good one but, it will depend on the opinion on how of the existing flow needs to be maintained.
Skip opening a file (via the `checkBox_FilelessOpen`), clean version with only changes inside `NewFileDialog::loadFile`, without calling `openNewFile`, `displayInitialOptionsDialog` and `setupAndStartAnalysis`. Skipping directly to `finalizeOpen`
**Checklist**
> Ticket#174/Skip opening a file, clean version

- src/dialogs/NewFileDialog.cpp
- src/dialogs/NewFileDialog.h
- src/dialogs/NewFileDialog.ui
Disable and hide file related widgets when we are not going to open a file, while maintaining the dialog geometry
from issue: https://github.com/radareorg/iaito/issues/179
**Checklist**
> disable and hide widgets when we are not going to open a file

- .github/workflows/ci.yml
As it has been requested:
https://github.com/radareorg/iaito/issues/170#issuecomment-2130003128
This PR intends to change all artifact names from `m1` to `arm64`.
This does not change the download URL to install radare2, so it is not required to wait until this gets merged and released:
https://github.com/radareorg/radare2/pull/23845
> Rename m1 to arm64 for mac builds

- src/widgets/RegistersWidget.cpp
radare2 prefixes register values with 0x in the output of `drrj` since version 5.9.0 (commit https://github.com/radareorg/radare2/commit/e424a1b611d3e16abbcaeef288e7658c07a513e0).
**Checklist**
Right now the registers widget displays value with double 0x prefix, this commit fixes it.
Before:
After:
> Remove extra "0x" prefix when displaying registers

- .github/workflows/ci.yml
- .gitignore
- dist/macos/Makefile
- dist/macos/doc/README.txt
- dist/macos/scripts/command.sh
- dist/macos/scripts/embed-radare2.sh
- src/Iaito.pro
- src/IaitoApplication.cpp
- src/core/Iaito.cpp
Reuse the `radare2.pkg` build but moving to the corresponding folders.
```sh
R2_BINDIR="${APPDIR}/Contents/Helpers"
R2_LIBDIR="${APPDIR}/Contents/Frameworks"
R2_LIBR_PLUGINS="${APPDIR}/Contents/PlugIns/radare2" # only the binaries
R2_PREFIX="${APPDIR}/Contents/Resources/radare2"
```
Also `R2_PREFIX` keeps the typical folder structure thanks to symlinks.
It has been found some traces of this in the cpp code, but I opted to reimplement using environment variables at application start, so running any other radare2 command will work from inside iaito.
Also include latest [r2ai-decai](https://github.com/radareorg/r2ai/tree/master/decai) release.
For **macOS ARM64** to build, it requires a radare2 pkg build that include this PRs:
- https://github.com/radareorg/radare2/pull/23885
- …
> Bundle radare2 inside the macOS app

- .github/workflows/ci.yml
- dist/macos/Makefile
- dist/macos/iaito.entitlements
For the branch and PR workflows the macOS artifacts have the following changes:
- Changed format from DMG to ZIP
- Added ad-hoc sign deep to the whole app bundle
For the release assets:
- Create a DMG from the zip assets
- Remove the `README*.txt`
- Added sign for the app bundle
- Added sign for the dmg file
- Added commented code for notarize the dmg file
> Sign macos release builds

- .github/workflows/ci.yml
- dist/macos/scripts/embed-radare2.sh
- Updated CI radare to 6.0.0
- Fix w64 artifact contents (now only contain the resulted build files)
- Fixed issue when embedding static r2 binaries
- Added a workaround for https://github.com/radareorg/radare2/commit/266319b0902603545d94dc35f9c4404b0a2b3a36
> Update radare2 to version 6.0.0

- src/common/Configuration.cpp
- src/common/TempConfig.cpp
- src/widgets/BoolToggleDelegate.cpp
> Fix Qt5/Qt6 build compatibility by replacing QVariant::typeId() with version-safe helper

- .github/workflows/ci.yml
- dist/debian/CONFIG
Update deb builds to use Ubuntu 22.04 and QT6.
To support from debian 12 and ubuntu 22.04.
This should fix #244
> Update deb builds to use QT6
